-- liquibase formatted sql

-- changeset Olakunle.Thompson:1665657625203-1
CREATE TABLE "engine_config" ("id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, "final_score" numeric(19, 2), "is_enabled" BOOLEAN, "product_id" BIGINT, "relative_score" numeric(19, 2), "segment_type" INTEGER, "variable_type" INTEGER, "variable_weightage" numeric(19, 2), CONSTRAINT "engine_config_pkey" PRIMARY KEY ("id"));

-- changeset Olakunle.Thompson:1665657625203-2
ALTER TABLE "engine_config" ADD CONSTRAINT "productid_variable_segment_unique" UNIQUE ("product_id", "variable_type", "segment_type");

